### ISSUE TITLE
Autologin ipadress needs to be set for autologin to work .... (Auto-login IP Address (Optional):)

### ISSUE THREAD

**Issue by Audun1555** [DNNCommunity/DNN.ActiveDirectory#20]
If this configuration field is not set - autologin does not work with DNN9
Seems like the implementation/logic also is weak - should be able to define ipnet with mask.
Now it just converts your IP to a long and checks if its equal to one of the ipadresses in the list(converted to long) or greater/less than the adresses(converted to long) in the provided range.

Set to 1.0.0.1-255.255.255.255 autologin works ....

**Comment by sawest** [comment]
@Audun1555 
Are you suggesting that for range we add the ability to enter something such as: 192.168.1.0/32 instead of 192.168.1.1-192.168.1.254?

Even with this implementation, will still need to check if local IP is within range after masking.  This feature will just clean up the ranges a bit and in some cases make adding ranges a little simpler.  Is this correct?

Trying to clarify before making code change.  Thanks for your input @Audun1555!

**Comment by Audun1555** [comment]
Hi, that was my initial thought - a more network/tcpip like approach ...
Maybe IPv6 should also be taken into account?

A few hints here on how this can be implemented:
https://stackoverflow.com/questions/2138706/how-to-check-a-input-ip-fall-in-a-specific-ip-range

On short term the most important thing to fix is to make autologin work if the configuration is left blank. (as stated in the documentation this should autologin everyone - guess many people give up in trying to set it up now - when autologin does not work without a defined IP range that the clients local ip is in the range)

//Audun

**Comment by sawest** [comment]
Release 6.1.2 has an added feature to enable/disable auto login and the auto-login ip address field is only used if auto login is enabled.  When enabled and ip address field is left blank, everyone is automatically logged on.

I will add a separate feature request for ip address mask.
