### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/DNN.ActiveDirectory#23]
I'm on a test machine and have installed the latest version 6.0.2

I tried to login with my AD account an get this error in the event logs:

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:7828c922-67ec-48b6-bc4c-5dc63a4c5534

AssemblyVersion:8.0.3

PortalId:1

UserId:-1

TabId:82

RawUrl:/Login?returnurl=%2f

Referrer:https://www.mywebsite.com/Login?returnurl=%2f

UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko

ExceptionHash:wtHTwdYNpUFiFbROWVt6Yw==

Message:This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to "true" in the configuration file.

StackTrace:

InnerMessage:This provider is not configured to allow password resets. To enable password reset, set enablePasswordReset to "true" in the configuration file.

InnerStackTrace:

   at System.Web.Security.SqlMembershipProvider.ResetPassword(String username, String passwordAnswer)
   at System.Web.Security.MembershipUser.ResetPassword(String passwordAnswer)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.ResetAndChangePassword(UserInfo user, String newPassword, String answer)
   at DotNetNuke.Entities.Users.UserController.ChangePasswordByToken(Int32 portalid, String username, String newPassword, String resetToken)
   at DotNetNuke.Authentication.ActiveDirectory.AuthenticationController.RandomizePassword(MembershipUser aspNetUser, UserInfo objUser, String& strPassword)
   at DotNetNuke.Authentication.ActiveDirectory.AuthenticationController.AuthenticateUser(UserInfo objUser, ADUserInfo objAuthUser, UserLoginStatus& loginStatus, String ipAddress)
   at DotNetNuke.Authentication.ActiveDirectory.AuthenticationController.ManualLogon(String userName, String strPassword, UserLoginStatus& loginStatus, String ipAddress)
   at DotNetNuke.Authentication.ActiveDirectory.Login.cmdLogin_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: INTRANETDEV

**Comment by sawest** [comment]
Sounds like you don't have the enablePasswordReset attribute in your web.config file set to true.  You can find this instance in the web.config file for the entire DNN instance.  Search for enablePasswordReset.  Once you find the attribute, set it to true and restart the website.

**Comment by muddeatr** [comment]
OK I'm only on a test system so I can try that but I'm not resetting my password? All I did was upgrade the module. Why do I need to allow reset?

**Comment by sawest** [comment]
Not knowing much about your environment or how you have this module configured I can tell you this...
When a user logs in the first time (no local DNN user) then a local DNN user is created mirroring the AD user account but with a random password (password cannot match the AD password).

Each log in after the initial (local DNN user exists) then a new random password is created and the local DNN user's password gets the new random password.  I assume this is for security since you never use the local DNN password so it can be random and constantly changed.

DNN uses the ASP membership provider for authentication.  If your web.config settings disables ASP from resetting passwords then when the new random password is created and this module attempts to change the old to the new you will receive the error you are getting.

There is probably some code revision that could be done here but in the mean time I hope this helps you understand the problem.

**Comment by muddeatr** [comment]
Thanks for the explanation. One last question then. Why didn't I have an issue until I upgraded to 6.0.2? I am currently running 5.0.3 in my production environment with the password reset set to false.

**Comment by sawest** [comment]
Again, not sure of your settings or environment.  There are some settings that would cause the module to bypass this particular piece of code.  Also, from what I have read above, you are not upgrading exactly (loading newer version over older working version).  You simply have 2 different modules on 2 different servers running on 2 different DNN instances.  Now if you get 5.0.3 working on the test environment, then upgrade to 6.0.2 and then it breaks, we would have something to go on.

**Comment by muddeatr** [comment]
But that's exactly what's been happening. 

My test machine is just a copy of my production that I keep replacing so I can test upgrades. I am currently running 5.0.3 and I am "testing" the upgrade on my test machine to 6.0.2 and that's when I get that error.

I even tried going from 5.0.3 to 5.0.6 and have issues with 5.0.6 not saving the settings correctly. So I just tried to go from 5.0.3 to 6.0.2.

**Comment by sawest** [comment]
Thats good information to know.  When I get time, I will dig around in 5.0.3 code and see what the difference is.

**Comment by muddeatr** [comment]
Thanks a bunch for all your help !! 👍

**Comment by muddeatr** [comment]
Does this AD Module work with the password format set to hashed in the config file?

**Comment by muddeatr** [comment]
When I set the password format to hashed I get an error "Hashed passwords cannot be retrieved. Either set the password format to different type, or set enablePasswordRetrieval to false."

When I set the enablePasswordRetrieval to false I get an error trying to login with the AD module saying "This Membership Provider has not been configured to support password retrieval."

**Comment by sawest** [comment]
While bug fixing I took a deeper look into this issue as I and others have encountered it in the past.  I will document here and in this forum: [http://www.dnnsoftware.com/forums/forumid/89/threadid/488876/scope/posts].

First the process....
First time user logins:  when a user logs in, they are authenticated against AD and then a DNN user is created (if doesn't exist) with a random password.  

Not first time user logs in:  if the local DNN user exists after AD authentication, then for update purposes, the validated DNN user needs to be retrieved.  In order to retrieve it, the "ValidateUser" method is 
used [http://www.dotnetnukeru.com/dnndocs/api/html/M_DotNetNuke_Entities_Users_UserController_ValidateUser_2.htm].  
Here is where things get complicated.  In order to validate the user, the local DNN password must be provided.  The password was created at random and the module has no way of knowing the password.  So how does the module retrieve the password for user validation?  2 Options....

1.  Retrieve the password from the user using the System.Web.Security.MembershipUser.getPassword() method.  This requires that the enablePasswordRetrieval attribute in web.config be set to true.  Also required is the attribute passwordFormat to 'clear' or 'encrypted'.  Hashed passwords cannot be retrieved.  I believe that this module originally was created before the hashed option and therefore only checked for the enablePasswordRetrieval attribute before attempting the get the password (new check will be added in next pull request).  If enablePasswordRetrieval is false and/or passwordFormat is hashed then option 2 must be used.

2.  Create a new random password on the fly, change the users password to the new one, use the new password to validate the user.  In the event that enablePasswordRetrieval and/or passwordFormat is hashed, then the system cannot retrieve the existing password.  Exceptions will be thrown, tears shed, and many questions asked.  Instead, a new password is created.  Then the DNN user controller method "ChangePasswordByToken" is used to change the users password.  HOWEVER, now the enablePasswordReset attribute must be set to true in web.config to allow this.  If false then an exception will be thrown, tears shed, etc.

Conclusion,
For this module to work correctly, you must: 
1. set enablePasswordRetrieval = false & set passwordFormat = hashed & set enablePasswordReset = true
2. set enablePasswordRetrieval = true & set passwordFormat  = clear or encrypted

Next pull request will include a new check for passwordFormat = hashed so that if it is set to hashed no password retrieval will be attempted.

**Comment by sawest** [comment]
fixed in pull request #27
